#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.


rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read -r file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

while read -r file
do
	echo "$file"
	echo "$1"
	case "$1" in
		"s")      
			nFile="$(echo "$file" | sed -E 's/^.*\/(.*$)/\1/')"
			mimeType="$(xdg-mime query filetype "$file")"
			echo "nFile: $nFile, mimeType: $mimeType"
			if [ -e "$HOME"/"$nFile" ]; then
				echo "$nFile already exists!"
			else
				if ! echo "$nFile" | grep -q "\..*$"; then
					case "$mimeType" in
						image/png) nFile="$nFile.png" ;;
						image/jpeg) nFile="$nFile.jpg" ;;
						image/gif) nFile="$nFile.gif" ;;
					esac
				fi
				cp -v "$file" "$HOME"/"$nFile"
			fi
			;;
		"y")      
			xclip -sel c -t "$(xdg-mime query filetype "$file")" "$file" ;;
		"C-e")      
			while read -r file; do urxvtc -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
		"C-g")      
			tr '\n' '\0' | xargs -0 gimp & ;;
		"C-r")      
			while read -r file; do rawtherapee "$file" & done ;;
		"C-comma")  
			rotate 270 ;;
		"C-period") 
			rotate  90 ;;
		"C-slash")  
			rotate 180 ;;
		"d")
			[ -d /tmp/sxiv ] || mkdir /tmp/sxiv
			echo "$file"
			mv "$file" /tmp/sxiv
			;;
	esac
done
